config:
  version-candidate: ./VERSION
build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          for i in {1..30}
          do
            echo "$i iterations complete"
            sleep 0.1s
          done
release: 
  filter:
    owner: Phillammon
    branch: master
  validation:
    job:
      machine: graknlabs-ubuntu-20.04
      script: |
        echo Released!
