build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          for i in {1..300}
          do
            echo "Welcome $i times"
            sleep 0.1s
          done
