build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: |
          for i in {1..300}
          do
            echo "padding padding padding padding padding padding padding padding padding padding padding padding padding padding padding padding padding padding Welcome but this is an extremely long line that goes beyond default console width just in case to test that $i times"
            sleep 0.1s
          done
