build:
  quality:
      test-job:
        machine: graknlabs-ubuntu-20.04
        script: echo Hello\n
          echo This is going to cause an error\n
          echo On the next line, which is line 4 of the script\n
          jfgkoasjgsfakgopfas\n
          echo We shouldn't get here\n
